// This file is automatically generated. Do not edit it directly.
// NOTE: Supabase is now optional since we're using PHP backend
// This client is kept for backward compatibility but may not be fully functional
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Only create client if both URL and key are provided
// Otherwise, create a dummy client that won't crash but won't work
let supabaseInstance: SupabaseClient<Database> | null = null;

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  try {
    supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } catch (error) {
    console.warn('Failed to initialize Supabase client:', error);
  }
}

// Export a proxy object that safely handles null cases
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(target, prop) {
    if (!supabaseInstance) {
      // Return no-op functions if Supabase is not configured
      if (typeof prop === 'string' && ['channel', 'from', 'functions'].includes(prop)) {
        return () => ({
          subscribe: () => ({}),
          on: () => ({}),
          removeChannel: () => {},
          select: () => ({
            eq: () => ({
              order: () => ({
                limit: () => Promise.resolve({ data: null, error: null }),
              }),
            }),
            update: () => ({
              eq: () => Promise.resolve({ error: null }),
            }),
          }),
          invoke: () => Promise.resolve({ error: { message: 'Supabase not configured' } }),
        });
      }
      return () => {};
    }
    const value = (supabaseInstance as any)[prop];
    return typeof value === 'function' ? value.bind(supabaseInstance) : value;
  }
});